const data = {
  cards: [
    {
      name: "Sports that require special shoes",
      answers: [
        "wrestling",
        "football",
        "baseball",
        "basketball",
        "soccer",
        "golf",
        "bowling",
        "rollerskating",
        "icehockey",
        "track",
      ],
    },
    {
      name: "Things in a Desert",
      answers: [
        "cactus",
        "sand",
        "camels",
        "snakes",
        "scorpions",
        "lizards",
        "oasis",
        "heat",
        "buzzards",
        "tumbleweeds",
      ],
    },
    {
      name: "Things you can order at McDonalds (items, not meals)",
      answers: [
        "bigmac",
        "hamburger",
        "cheeseburger",
        "fries",
        "milkshake",
        "mcflurry",
        "quarterpounder",
        "mcnuggets",
        "sausagemcmuffin",
      ],
    },
    {
      name: "Jungle Animals",
      answers: [
        "monkeys",
        "lions",
        "tigers",
        "giraffe",
        "elephant",
        "zebra",
        "leopard",
        "crocodile",
        "gorilla",
        "snake",
      ],
    },
    {
      name: "States that border an ocean",
      answers: [
        "california",
        "oregon",
        "washington",
        "alaska",
        "hawaii",
        "florida",
        "maine",
        "massachusetts",
        "connecticut",
        "virginia",
      ],
    },
    {
      name: "Pizza Toppings",
      answers: [
        "pepperoni",
        "canadianbacon",
        "anchovies",
        "cheese",
        "olives",
        "mushrooms",
        "sausage",
        "onions",
        "peppers",
        "pineapple",
      ],
    },
    {
      name: "Yellow Foods (and condiments)",
      answers: [
        "lemon",
        "banana",
        "corn",
        "squash",
        "pineapple",
        "cheese",
        "eggs",
        "yellowpeppers",
        "mustard",
        "butter",
      ],
    },
    {
      name: "Fast Food Chains",
      answers: [
        "mcdonalds",
        "tacobell",
        "carlsjr",
        "kfc",
        "burgerking",
        "wendys",
        "jackinthebox",
        "arbys",
        "longjohnsilvers",
        "subway",
      ],
    },
    {
      name: "Buttons to press on a VCR",
      answers: [
        "play",
        "stop",
        "rewind",
        "fastforward",
        "pause",
        "record",
        "program",
        "eject",
        "power",
        "channel",
      ],
    },
    {
      name: "Full Length Disney Cartoons",
      answers: [
        "cinderella",
        "dumbo",
        "littlemermaid",
        "snowwhite",
        "tarzan",
        "101dalmations",
        "bambi",
        "fantasia",
        "beautythebeast",
        "dinosaur",
      ],
    },
    {
      name: "Winnie The Pooh Characters",
      answers: [
        "pooh",
        "tigger",
        "kanga",
        "roo",
        "rabbit",
        "owl",
        "piglet",
        "gopher",
        "christopherrobin",
        "eeyore",
      ],
    },
    {
      name: "Types of sports balls",
      answers: [
        "pingpong",
        "football",
        "soccer",
        "baseball",
        "tennis",
        "golf",
        "volleyball",
        "basketball",
        "softball",
        "mushball",
      ],
    },
    {
      name: "Types of Candy Bars",
      answers: [
        "twix",
        "babyruth",
        "snickers",
        "hersheys",
        "3musketeers",
        "butterfinger",
        "crunch",
        "almondjoy",
        "mounds",
        "payday",
      ],
    },
    {
      name: "California Cities that start with the letter S",
      answers: [
        "selma",
        "sanger",
        "sacramento",
        "salinas",
        "sansimeon",
        "sanfrancisco",
        "stockton",
        "sandiego",
        "santacruz",
        "santabarbara",
      ],
    },
  ],
};

export default data;
